StringTable {
 Item "GBRS-RadarStation_US_Name" {
  "US Ground Radar Station (RPL-5)"
 }
 Item "GBRS-RadarStation_USSR_Name" {
  "USSR Ground Radar Station (TPN-19)"
 }
 Item "GBRS-RadarStation_US_Desc" {
  "Placeable US approach radar station with active search and track."
 }
 Item "GBRS-RadarStation_USSR_Desc" {
  "Placeable USSR approach radar station with active search and track."
 }
}
