SCR_PlaceableEntitiesRegistry {
 m_sAddon "Groundbasedradarstation"
 m_bExposed 1
 m_Prefabs {
  "{69FCEDCEA0010003}PrefabsEditable/Auto/Compositions/Misc/FreeRoamBuilding/E_RadarStation_S_US_01.et"
  "{69FCEDCEA0010004}PrefabsEditable/Auto/Compositions/Misc/FreeRoamBuilding/E_RadarStation_S_USSR_01.et"
 }
}
